### ISSUE TITLE
I am using ruby 2.1.5 .  Ez mail comes up with "to_a" errors with Ruby 2.1.5

### ISSUE THREAD

**Issue by ToddGRobertson** [djberg96/ez-email#1]
I used the old code for 1.9.... whatever I used programming a few years ago and it worked fine then, but not anymore.

Todd Robertson
Concord, MA

**Comment by djberg96** [comment]
Can you paste the exact error you're getting?

**Comment by ToddGRobertson** [comment]
I will do it Tuesday when I am at work.  Using it there.

-----Original Message-----

**Comment by djberg96** [comment]
Any word on the error?

**Comment by ToddGRobertson** [comment]
I have just been writing code at work and using a working mail method and never went back to it.

-----Original Message-----

**Comment by djberg96** [comment]
Ok, closing.
